import type { RouteManifest } from '../router/routeTypes';
import { analyzeInjection } from '../injection/analyzeInjection';
import { getInputTypeForMethod } from '../runtime/inputType';
import fs from 'node:fs/promises';
import path from 'node:path';

interface RouteTypeInfo {
  method: string;
  urlPath: string;
  inputType: string; // TypeScript type string for input
  outputType: string; // TypeScript type string for output (unknown if can't infer)
  filePath: string;
}

/**
 * 从路由清单生成类型定义文件
 */
export async function generateTypes(
  routes: RouteManifest,
  rootDir: string,
  outputPath: string,
): Promise<void> {
  const routeTypes: RouteTypeInfo[] = [];

  for (const route of routes) {
    const absolutePath = path.resolve(rootDir, route.filePath);
    let code: string;
    try {
      code = await fs.readFile(absolutePath, 'utf-8');
    } catch {
      continue;
    }

    const meta = analyzeInjection(code, route.method);
    const inputType = buildInputType(meta, route.method);

    routeTypes.push({
      method: route.method,
      urlPath: route.urlPath,
      inputType,
      outputType: 'unknown',
      filePath: route.filePath,
    });
  }

  const content = buildTypeFile(routeTypes);
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, content, 'utf-8');
}

function buildInputType(
  meta: { params: Array<{ name: string; type: string; typeName?: string }> },
  method: string,
): string {
  if (meta.params.length === 0) return 'void';

  const source = getInputTypeForMethod(method);
  const relevantParams = meta.params.filter((p) => p.type === source);

  if (relevantParams.length === 0) return 'void';

  // If there's a type name, reference it
  if (relevantParams.length === 1 && relevantParams[0].typeName) {
    return relevantParams[0].typeName;
  }

  return 'Record<string, unknown>';
}

function buildTypeFile(routes: RouteTypeInfo[]): string {
  const lines: string[] = [
    '// Auto-generated by faapi — do not edit',
    '// eslint-disable-next-line @typescript-eslint/no-namespace',
    'export namespace FaapiRoutes {',
    '',
  ];

  for (const route of routes) {
    const key = routeKey(route.method, route.urlPath);
    lines.push(`  interface ${key} {`);
    lines.push(`    method: '${route.method}';`);
    lines.push(`    path: '${route.urlPath}';`);
    lines.push(`    input: ${route.inputType};`);
    lines.push(`    output: ${route.outputType};`);
    lines.push('  }');
    lines.push('');
  }

  // Build route map type
  lines.push('  interface Routes {');
  for (const route of routes) {
    const key = routeKey(route.method, route.urlPath);
    lines.push(`    '${route.method} ${route.urlPath}': ${key};`);
  }
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Generate typed client interface
  lines.push('export interface FaapiClient {');
  for (const route of routes) {
    lines.push(
      `  ${methodName(route.method)}('${route.urlPath}'${route.inputType === 'void' ? '' : ', input'}): Promise<${route.outputType}>;`,
    );
  }
  lines.push('}');

  return lines.join('\n');
}

export function routeKey(method: string, urlPath: string): string {
  const sanitized = urlPath
    .replace(/^\//, '')
    .replace(/\/:/g, '_')
    .replace(/\//g, '_')
    .replace(/-/g, '_');
  return `${method}_${sanitized || 'root'}`;
}

export function methodName(method: string): string {
  return method.toLowerCase();
}
